//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseFlow()
        {
            this.BaseAlternativeFlows = new HashSet<BaseAlternativeFlow>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string FlowChartPath { get; set; }
        public int DiagramElementStateId { get; set; }
        public int ScreenElementStateId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UseCase UseCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseAlternativeFlow> BaseAlternativeFlows { get; set; }
        public virtual ElementState DiagramElementState { get; set; }
        public virtual ElementState ScreenElementState { get; set; }
    }
}
