//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinnesRulesMessages
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int MessageId { get; set; }
        public int BusinessRuleId { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual BusinessRule BusinessRule { get; set; }
        public virtual Project Project { get; set; }
    }
}
