//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectsForStateChange
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int ObjectStatesChangeId { get; set; }
        public int ObjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ObjectStatesChange ObjectStatesChange { get; set; }
        public virtual Object Object { get; set; }
    }
}
