//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectStatesChange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectStatesChange()
        {
            this.ObjectsForStateChanges = new HashSet<ObjectsForStateChange>();
            this.RolesForStateChanges = new HashSet<RolesForStateChange>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int PredecessorId { get; set; }
        public int SuccessorId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ObjectState Predecessor { get; set; }
        public virtual ObjectState Succesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectsForStateChange> ObjectsForStateChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesForStateChange> RolesForStateChanges { get; set; }
    }
}
